language: node_js
node_js: 6
cache: yarn
before_script: 
  - cd app
  - npm install eslint
script: yarn lint

# NOTE - npm tests not currently working
# dist: trusty
# sudo: required
# node_js: 6
# script:
# - npm run test

# cache:
#   directories:
#   - node_modules
#   - web/node_modules
#   - bot/node_modules
# env:
#   global:
#   - CF_APP=TODO
#   - CF_API=TODO
#   - CF_ORGANIZATION=TODO
#   - CF_SPACE=TODO
# before_deploy: npm install -g https://github.com/germanattanasio/cf-blue-green
# deploy:
#   provider: script
#   script:
#   - cf-blue-green-travis
#   on:
#     branch: master
#     repo: watson-developer-cloud/TODO
#   skip_cleanup: true
# notifications:
#   email: false
