---
version: '3'
services:

  cloudant-developer:
    build:
      context: .
    image: ibmcom/cloudant-developer:latest
    container_name: cloudant-developer
    hostname: developer.local
    ports:
      - "8080:80"
    volumes:
      - cloudant-developer:/srv
    network_mode: bridge

volumes:
  cloudant-developer:
